# This is a config for E2B sandbox template.
# You can use template ID (pk133mytfua2fq2zkpay) or template name (open-lovable-nextjs-template-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("open-lovable-nextjs-template-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("open-lovable-nextjs-template-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('open-lovable-nextjs-template-2')

team_id = "5adce3be-d046-4dea-9912-df5bc0d12344"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "open-lovable-nextjs-template-2"
template_id = "pk133mytfua2fq2zkpay"
